global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:

  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']


  - job_name: 'pre-nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.100.136:9100', '192.168.100.147:9100', '192.168.100.251:9100']


  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'pre-cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.100.136:8082', '192.168.100.147:8082', '192.168.100.251:8080']

  - job_name: 'pre-mysql'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.100.251:9104']

  - job_name: 'pre-emqx'
    metrics_path: '/api/v4/emqx_prometheus'
    params:
      type: ['prometheus']
    basic_auth:
      username: 'admin'
      password: 'Pji210608'
    scrape_interval: 5s
    honor_labels: true
    static_configs:
     # EMQX IP address and port
      - targets: ['192.168.100.136:18083', '192.168.100.147:18083', '192.168.100.251:18083']
  
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
      
  - job_name: 'pushgateway'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']



alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - 'alertmanager:9093'

#  - job_name: 'nginx'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['nginxexporter:9113']

#  - job_name: 'aspnetcore'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['eventlog-proxy:5000', 'eventlog:5000']
